settings:
  digits: '3'
  parent: SIDD
  prefix: CORALS-REQ
  sep: '-'
attributes:
  defaults:
    Fully Decomposed: false
    Metric: TBD
    Range: TBD
    Verification: |
      Demonstration, Inspection, Manual Test, or Automated Test
    Subsystem: |
      Structures, Command and Control, or Electrical
  reviewed:
  - Fully Decomposed
  - Metric
  - Range
  - Subsystem
  - Verification
  publish:
  - Metric
  - Range
  - Subsystem
  - Verification
